export const executeHelp = (): string =>
  [
    'USAGE',
    '  composio execute <slug> --session-id <session_id> [-d, --data text] [--file path] [--dry-run] [--get-schema]',
    '  composio execute --parallel --session-id <session_id> <slug> -d <text> <slug> -d <text> ...',
    '',
    'DESCRIPTION',
    '  Execute a tool by slug.',
    '  Validates inputs against cached schemas and checks the session connection automatically; just try it and it will tell you what to fix.',
    '  Sessions are created by your app/backend; this CLI only operates on an existing Tool Router session.',
    '',
    'ARGUMENTS',
    '  <slug>                    Tool slug for single execute, or repeated TOOL_SLUG -d <text> groups when using -p/--parallel',
    '',
    'OPTIONS',
    '  --session-id <session_id> Existing Tool Router session id.',
    '  -d, --data <text>         JSON or JS-style object arguments, e.g. -d \'{ repo: "foo" }\', @file, or - for stdin',
    '  -p, --parallel            Execute repeated TOOL_SLUG -d <text> groups concurrently',
    '  --file <path>             Inject a local file path into the single file_uploadable input',
    '  --get-schema              Print the CLI-facing input schema without executing',
    '  --dry-run                 Validate and preview the tool call without executing',
    '  --account <text>          Connected account selector inside the provided session',
    '',
    'FLAGS',
    '  --skip-connection-check   Skip the connected-account check',
    '  --skip-tool-params-check  Skip input validation against cached schema',
    '  --skip-checks             Skip both checks above',
    '',
    'EXAMPLES',
    '  # Send an email',
    '  composio execute GMAIL_SEND_EMAIL --session-id trs_... -d \'{ recipient_email: "a@b.com", subject: "Hello", body: "World" }\'',
    '',
    '  # Create a GitHub issue',
    '  composio execute GITHUB_CREATE_ISSUE --session-id trs_... -d \'{ owner: "acme", repo: "app", title: "Bug report", body: "Steps to reproduce..." }\'',
    '',
    '  # Preview what a tool call would send without executing',
    '  composio execute SLACK_SEND_A_MESSAGE_TO_A_SLACK_CHANNEL --session-id trs_... --dry-run -d \'{ channel: "general", text: "Hello team" }\'',
    '',
    '  # Check what inputs a tool needs',
    '  composio execute GMAIL_SEND_EMAIL --session-id trs_... --get-schema',
    '',
    '  # Read arguments from a file',
    '  composio execute GITHUB_CREATE_ISSUE --session-id trs_... -d @issue.json',
    '',
    '  # Read arguments from stdin',
    '  printf \'{"recipient_email":"a@b.com"}\' | composio execute GMAIL_SEND_EMAIL --session-id trs_... -d -',
    '',
    '  # Execute multiple tools concurrently',
    '  composio execute -p --session-id trs_... GMAIL_SEND_EMAIL -d \'{ recipient_email: "a@b.com" }\' GITHUB_CREATE_AN_ISSUE -d \'{ owner: "acme", repo: "app", title: "Bug" }\'',
    '',
    'SEE ALSO',
    '  composio search "<query>" --session-id trs_...    Find tool slugs by use case',
  ].join('\n');
