export const proxyHelp = (): string =>
  [
    'USAGE',
    '  composio proxy <url> --toolkit <text> --session-id <session_id> [-X method] [-H header]... [-d data]',
    '',
    'DESCRIPTION',
    '  curl-like access to any toolkit API through Composio using your connected account.',
    '  Composio handles authentication; just provide the full URL and toolkit.',
    '  The provided session must already have the relevant connected account.',
    '',
    'ARGUMENTS',
    '  <url>                     Full API endpoint URL',
    '',
    'OPTIONS',
    '  --session-id <session_id> Existing Tool Router session id.',
    '  -t, --toolkit <text>      Toolkit slug whose connected account should be used',
    '  -X, --method <method>     HTTP method (GET, POST, PUT, DELETE, PATCH)',
    '  -H, --header <header>     Header in "Name: value" format. Repeat for multiple.',
    '  -d, --data <data>         Request body as raw text, JSON, @file, or - for stdin',
    '  --skip-connection-check   Skip the connected-account check',
    '',
    'EXAMPLES',
    '  composio proxy https://gmail.googleapis.com/gmail/v1/users/me/profile --toolkit gmail --session-id trs_...',
    '  composio proxy https://gmail.googleapis.com/gmail/v1/users/me/drafts --toolkit gmail --session-id trs_... \\',
    '    -X POST -H \'content-type: application/json\' -d \'{"message":{"raw":"..."}}\'',
  ].join('\n');
