export const rootHelp = (): string =>
  [
    'Composio CLI - operate on existing Tool Router sessions.',
    '',
    'USAGE',
    '  composio <command> [options]',
    '',
    'ENVIRONMENT',
    '  COMPOSIO_API_KEY            Required project API key.',
    '  COMPOSIO_BASE_URL           Optional API base URL override for development.',
    '',
    'SESSION MODEL',
    '  Every command requires --session-id <session_id>.',
    '  Sessions are created by your app/backend; this CLI only operates on an existing Tool Router session.',
    '  The CLI does not create sessions and does not accept user_id.',
    '',
    'COMMANDS',
    '  search    Find tools by use case across all toolkits/apps.',
    '  execute   Execute a tool by slug inside an existing session.',
    '  proxy     curl-like access to any toolkit API through Composio using your connected account.',
    '',
    'EXAMPLES',
    '  composio search "send an email" --session-id trs_...',
    '  composio execute GMAIL_SEND_EMAIL --session-id trs_... -d \'{ "recipient_email": "a@b.com" }\'',
    '  composio proxy https://gmail.googleapis.com/gmail/v1/users/me/profile --toolkit gmail --session-id trs_...',
    '',
    'HELP',
    '  composio search --help',
    '  composio execute --help',
    '  composio proxy --help',
  ].join('\n');

