export const searchHelp = (): string =>
  [
    'USAGE',
    '  composio search <query...> --session-id <session_id> [--toolkits text] [--limit integer]',
    '',
    'DESCRIPTION',
    '  Find tools by use case across all toolkits/apps.',
    '  Writes JSON output for agent consumption.',
    '  Sessions are created by your app/backend; this CLI only operates on an existing Tool Router session.',
    '',
    'ARGUMENTS',
    '  <query...>                 One or more semantic use-case queries (e.g. "send an email", "create github issue")',
    '',
    'OPTIONS',
    '  --session-id <session_id>  Existing Tool Router session id.',
    '  --toolkits <text>          Filter by toolkit slugs, comma-separated',
    '  --limit <integer>          Maximum number of results (1-1000)',
    '',
    'EXAMPLES',
    '  # Find tools for a use case',
    '  composio search "send an email" --session-id trs_...',
    '  composio search "send an email" "create github issue" --session-id trs_...',
    '  composio search "my emails" "my github issues" --toolkits gmail,github --session-id trs_...',
    '  composio search "create issue" --toolkits github --session-id trs_...',
    '',
    '  # Cross-app workflow discovery',
    '  composio search "post a message to a slack channel" --session-id trs_...',
    '  composio search "add a row to google sheet" --session-id trs_...',
    '',
    '  # Narrow results to a specific toolkit',
    '  composio search "list calendar events" --toolkits google_calendar --limit 5 --session-id trs_...',
    '',
    'SEE ALSO',
    '  composio execute <slug> --session-id trs_... -d \'{ ... }\'    Run a tool from the results',
  ].join('\n');
